dist: xenial
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install pytest-cov
script:
  - pytest --cov-report=xml --cov=gnpy
after_success:
  - bash <(curl -s https://codecov.io/bash)
